### ISSUE TITLE
Decrease perl version

### ISSUE THREAD

**Issue by olegwtf** [pjlsergeant/p5-data-jsonschema-ajv#2]
I think the good practice is to use minimal perl version wich will support your module. More people will be able to use such module.

In the changelog I can see:

> Forced use to above Perl 5.20 ... 5.18 has some odd number issues, and
> also JavaScript::Duktape::XS is 5.18 and above anyway

I don't know which odd number issues did you mean.

As I see version may be descreased even to 5.14 (the first where `package Foo {}`  syntax was introduced).

In our project we are using 5.18 and this project is very big. So we can't just change perl version, this will require alot of hard testing. This is planned, but not now.

Can you please decrease perl version? 5.18 will be ok for me.

**Comment by vsespb** [comment]
+1

would it be possible to describe here exactly what is broken in 5.18?
I might help fixing it to stay in 5.18.

**Comment by olegwtf** [comment]
@pjlsergeant what do you think?

**Comment by pjlsergeant** [comment]
I think this is a great idea and I am desperately trying to find the time
and energy to reply :-)

**Comment by olegwtf** [comment]
Will it help you if I'll create pull request?

**Comment by pjlsergeant** [comment]
OK, done! 0.06 should be on the CPAN shortly: https://github.com/pjlsergeant/p5-data-jsonschema-ajv/blob/master/CHANGES

**Comment by olegwtf** [comment]
Thanks
